export const CHANGE_FOCUS = "CHANGE_FOCUS";
export const CHANGE_PAGE = "CHANGE_PAGE";
export const CHANGE_MODULE = "CHANGE_MODULE";
export const CHANGE_SECTION = "CHANGE_SECTION";
export const SLIDING_END = "SLIDING_END";